services:
  jekyll:
    image: jekyll/jekyll:4.2.0
    container_name: jtdub-jekyll
    command: jekyll serve --watch --drafts --future --host 0.0.0.0 --port 4000
    ports:
      - "4000:4000"
      - "35729:35729"  # LiveReload port
    volumes:
      - ..:/srv/jekyll:Z
      - ../vendor/bundle:/usr/local/bundle:Z
    environment:
      - JEKYLL_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
    stdin_open: true
    tty: true
    networks:
      - jekyll-network

networks:
  jekyll-network:
    driver: bridge
