- hosts: droplets

  tasks:
  - name: INSTALL GLUSTER PREREQUISITES
    apt:
      name:
      - software-properties-common
      update_cache: yes

  - name: INSTALL GLUSTER REPOSITORY
    ansible.builtin.apt_repository:
      repo: "ppa:gluster/glusterfs-7"
      codename: focal

  - name: INSTALL GLUSTER SERVER PACKAGES 
    apt:
      name:
      - glusterfs-server 
      update_cache: yes
    when: swarm == "worker"

  - name: START GLUSTERFS SERVICE
    ansible.builtin.service:
      name: glusterd.service
      state: started 
      enabled: yes 
    when: swarm == "worker"

  - name: SETUP GLUSTER PEER 
    gluster.gluster.gluster_peer:
      state: present 
      nodes:
      - "{{ hostvars['node1.infra'].ansible_host }}"
      - "{{ hostvars['node2.infra'].ansible_host }}"
    when: swarm == "worker"

  - name: SETUP GLUSTER VOLUME
    gluster.gluster.gluster_volume:
      state: present 
      name: swarm 
      bricks: /srv/swarm
      force: yes
      replicas: 2
      cluster:
      - "{{ hostvars['node1.infra'].ansible_host }}"
      - "{{ hostvars['node2.infra'].ansible_host }}"
    when: swarm == "worker"

  - name: START GLUSTER VOLUME
    gluster.gluster.gluster_volume:
      state: started 
      name: swarm 
    when: swarm == "worker"

  - name: INSTALL GLUSTER CLIENT
    apt:
      name:
      - glusterfs-client
      state: present
    when: swarm == "manager"

  - name: CREATE CLIENT DIRECTORY
    ansible.builtin.file:
      path: /srv/swarm
      state: directory
      mode: "0755"

  - name: MOUNT GLUSTERFS VOLUME
    ansible.posix.mount: 
      src: "{{ hostvars['node1.infra'].ansible_host }}:/swarm"
      path: /srv/swarm
      fstype: glusterfs 
      state: mounted
    when: swarm == "manager"
