title: jtdub.com
description:
  tales of wanderlust, random thoughts, and blogs about technology; specifically linux, networking, automation, and software developmnet
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jtdub.com" # the base hostname & protocol for your site, e.g. http://example.com
plugins:
  - jekyll-feed


exclude:
- scripts
- tests
- deploy
