- hosts: master1.infra.jtdub.com 

  tasks:
  - name: FETCH JTDUB.COM GIT REPOSITORY
    ansible.builtin.git:
      repo: git@github.com:jtdub/jtdub.com.git
      dest: /home/jtdub/jtdub.com
  
  - name: SET JTDUB.COM GIT REPOSITORY USER PERMISSIONS
    ansible.builtin.file:
      path: /home/jtdub
      owner: jtdub
      group: jtdub
      recurse: yes
      state: directory
      force: yes
