[tool.poetry]
name = "jtdub.com"
version = "1.0.0"
description = "jtdub.com ansible"
authors = ["jtdub <amascuba@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
ansible-base = "^2.10.15"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
