version: "3.9"
services:
  jekyll:
    image: jekyll/jekyll:latest
    volumes:
      - ..:/srv/jekyll
    command: jekyll serve
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
  nginx:
    image: nginx:latest
    volumes:
      - ../container_files/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    links:
      - jekyll
    depends_on:
      - jekyll
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
