version: "3.9"
services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: jekyell
    volumes:
      - ..:/srv/jekyll
    command: jekyll serve
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./container_files/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    links:
      - jekyll
    depends_on:
      - jekyll
