- hosts: master1.infra.jtdub.com 

  tasks:
  - name: FETCH JTDUB.COM GIT REPOSITORY
    ansible.builtin.git:
      repo: git@github.com:jtdub/jtdub.com.git
      dest: /home/jtdub/jtdub.com
  
  - name: SET JTDUB.COM GIT REPOSITORY USER PERMISSIONS
    ansible.builtin.file:
      path: /home/jtdub
      owner: jtdub
      group: jtdub
      recurse: yes
      state: directory
      force: yes

  - name: BUILD JTDUB.COM CONTAINER AND PUSH IT TO REGISTRY
    community.docker.docker_image:
      build:
        path: /home/jtdub/jtdub.com
      name: "localhost:5000/jtdub.com"
      tag: latest
      push: yes
      source: build
