---
layout: post
title: OSPF Area Types and LSA's
date: '2014-04-11'
author: jtdub
tags:
- OSPF
- CCNP SP Study Notes
- packetgeek.net
---

Link State Advertisement (LSA) Types have never been my strong suite. I made a visual representation of how they are forwarded to help me get a better grasp on them.
<br/>
<br/>
<div class="separator" style="clear: both; text-align: center;">
 <a href="/images/OSPF-Area-Types.png" imageanchor="1" style="margin-left: 1em; margin-right: 1em;">
  <img border="0" data-original-height="543" data-original-width="910" height="190" src="/images/OSPF-Area-Types.png" width="320"/>
 </a>
</div>
<br/>
<br/>
<li>
 Default - This isn't actually an LSA type. It's meant to represent a default route.
</li>
<br/>
<br/>
<li>
 Type 1 - Router Link - This is generated by a router and lists the neighboring routers and the cost of each router. This is only flooded within the area that the router interface exists in.
</li>
<br/>
<br/>
<li>
 Type 2 - Network Link - This is generated by the Designated Router (DR). This lists all routers within an adjacent segment. This is only flooded within the area that the router interface exists in.
</li>
<br/>
<br/>
<li>
 Type 3 - Network Summary - This is generated by an Area Border Router (ABR) and is advertised among all areas, except totally stubby areas and totally not-so-stubby areas.
</li>
<br/>
<br/>
<li>
 Type 4 - ASBR Summary - This is generated by an ABR informing other areas that an Autonomous System Border Router (ASBR) exists within it's network.
</li>
<br/>
<br/>
<li>
 Type 5 - External Link - This is generated by an ASBR and is flooded within its area. ABRs will also flood their connected areas with this type 5 LSA informing other areas that external networks exist within its area.
</li>
<br/>
<br/>
<li>
 Type 7 - NSSA External Link - This is generated by an ASBR participating in an not-so-stubby (NSSA) area. When the type 7 LSA reaches the ABR, It is converted to a type 5 LSA and forwarded to other areas informing them that an external network exists within its area.
</li>
<br/>
<br/>
When a type 5 LSA enters a stubby area, it's entered into the RIB as a default route, striping the type 5 LSA routes. Type 5 LSAs are also not forwarded to not-so-stubby areas. To get external routes
<i>
 INTO
</i>
an not-so-stubby area, the area has to be converted to a totally not-so-stubby-area, which will remove all summaries and inject a default route.
<br/>
<br/>
As you can see from the diagram, above, there are six area types.
<br/>
<br/>
<br/>
<li>
 Backbone Area
</li>
<br/>
<br/>
<br/>
<li>
 Standard Area
</li>
<br/>
<br/>
<br/>
<li>
 Not-so-stubby Area
</li>
<br/>
<br/>
<br/>
<li>
 Totally stubby Area
</li>
<br/>
<br/>
<br/>
<li>
 Totally not-so-stubby Area
</li>
<br/>
<br/>
All areas have to be directly connected to area 0, which is the backbone area. All routers that exist within only area 0 or within just a single area are called backbone routers. Routers that connect to multiple OSPF areas are called ABRs. Routers that are connected to an OSPF area
<i>
 AND
</i>
connected to an external routing protocol (EIGRP, ISIS, RIP, BGP, static routes, etc) are called ASBRS.
<br/>
<br/>
Stubby areas and totally stubby areas are areas that have one way in and one way out of an area. That is, they can't be connected to area 0 and any other area or external network at the same time, as a stubby and totally stubby area ABR will not forward type 5 LSAs to other areas. A totally stubby area will only have a default route injected into its network.
<br/>
<br/>
Not-so-stubby and totally not-so-stubby areas can be connected to external networks and will forward the type 7 LSAs beyond their area. When the type 7 LSAs reach an ABR, the ABR will convert them to type 5 and forward them to the other areas.
