- hosts: droplets
  connection: local
  gather_facts: false

  tasks:
  - name: CREATE DIGITAL OCEAN DROPLETS
    community.digitalocean.digital_ocean_droplet:
      state: present 
      name: "{{ inventory_hostname }}.{{ domain }}"
      oauth_token: "{{ do.api_key }}"      
      ssh_keys:
      - "{{ hostvars['localhost'].ssh_key_result.data.ssh_key.fingerprint }}" 
      size: "{{ size_id }}" 
      region: "{{ region_id }}"
      image: "{{ image_id }}"
      ipv6: yes
      private_networking: yes
      unique_name: yes
      wait_timeout: 500
    register: droplet

  - name: SET ANSIBLE_HOST 
    set_fact:
      ansible_host: "{{ droplet.data.droplet.networks.v4[1].ip_address }}"

  - name: CREATE DNS A RECORD
    community.general.cloudflare_dns:
      zone: "{{ domain }}" 
      record: "{{ inventory_hostname }}"
      type: A
      value: "{{ ansible_host }}"
      account_email: "{{ cloudflare.email }}"
      account_api_key: "{{ cloudflare.api_key }}"
    register: cloudflare_dns
