- hosts: droplets

  tasks:
  - name: INSTALL REQUIRED DOCKER STACK PYTHON PACKAGES
    pip:
      name:
      - jsondiff
      state: present
    when: swarm == "manager"

  - name: DEPLOY JTDUB.COM DOCKER STACK
    community.docker.docker_stack:
      state: present
      name: jtdub-com
      compose:
      - /home/jtdub/jtdub.com/docker/docker-compose.yaml
    when: swarm == "manager"