- hosts: droplets

  tasks:
  - name: CREATE DOCKER REGISTRY
    community.docker.docker_swarm_service:
      name: registry
      image: registry:latest
      state: present
      publish:
        published_port: 5000
        target_port: 5000
    when: swarm == "manager"
  
  - name: CREATE SSLBOT IMAGE AND PUSH IT TO REGISTRY
    community.docker.docker_image:
      build:
        path: /srv/swarm/jtdub.com/container_files/opensslbot
      name: "localhost:5000/sslbot"
      tag: latest
      push: yes
      source: build
    when: swarm == "manager"