on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
  - name: SETUP PYTHON 3.8 
    uses: actions/setup-python@v1 
    with:
      python-version: 3.8

  - name: INSTALL ANSIBLE
    run: |
      pip install --upgrade pip
      pip install ansible

  - name: DEPLOY SITE 
    uses: dawidd6/action-ansible-playbook@v2
    with:
      playbook: git.yml
      directory: ./deploy
      key: ${{secrets.SSH_PRIVATE_KEY}}
      inventory: |
        [all]
        master1.infra.jtdub.com ansible_ssh_user=root
