on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: DEPLOY SITE 
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: /home/runner/work/jtdub.com/jtdub.com/deploy/git.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [all]
            master1.infra.jtdub.com ansible_ssh_user=root
